branch-defaults:
  eb:
    environment: prod
    group_suffix: null
global:
  application_name: aa-ecommerce-chat-bot
  branch: null
  default_ec2_keyname: eb_sysops
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: avenida
  repository: null
  sc: git
  workspace_type: Application
